"use strict";
window.GameNightOnline = (() => {
  const G=GameNight,R=GameNightRoom;
  let root=null,unsubscribe=null,preferred='color-clash',notice='',noticeTimer=null,drawing=null;
  let brushColor='#173b35',brushWidth='6';
  const icons={'color-clash':'✳','crazy-eights':'8','go-fish':'♦','shut-box':'⚄','solitaire':'♠','sea-battle':'⌖','spectrum':'◴','connect-four':'●','memory':'✿','pig':'⚅','tic-tac-toe':'×','higher-lower':'↕'};
  const order=['imposter','pictionary','guess-who','mafia','color-clash','crazy-eights','go-fish','sea-battle','spectrum','liars-dice','dots-boxes','reversi','rock-paper-scissors','shut-box','connect-four','memory','pig','tic-tac-toe','higher-lower','solitaire'];
  Object.assign(icons,{'imposter':'◉','pictionary':'✎','guess-who':'◈','mafia':'♜','dots-boxes':'▦','reversi':'◐','rock-paper-scissors':'✌','liars-dice':'⚂'});
  function name(){try{return localStorage.getItem('gn-name')||'';}catch{return '';}}
  function saveName(n){try{localStorage.setItem('gn-name',n);}catch{}}
  function avatar(p,i){return `<span class="player-avatar avatar-${i%6}" aria-hidden="true">${G.esc(p.name.slice(0,1).toUpperCase())}</span>`;}
  function feedback(text){notice=text;render();clearTimeout(noticeTimer);noticeTimer=setTimeout(()=>{notice='';render();},3500);}
  async function copy(text){try{await navigator.clipboard.writeText(text);feedback('Copied! Send it to your friends.');}catch{feedback('Select the code above and copy it to send to your friends.');}}
  function inputs(){if(!root)return null;const stage=root.querySelector('.room-stage');if(!stage)return null;return {key:stage.dataset.key,values:[...stage.querySelectorAll('[data-field]')].map(e=>({field:e.dataset.field,value:e.value})),focus:document.activeElement?.dataset?.field};}
  function restore(saved){if(!saved)return;const stage=root.querySelector('.room-stage');if(stage?.dataset.key!==saved.key)return;for(const x of saved.values){const el=stage.querySelector(`[data-field="${x.field}"]`);if(el)el.value=x.value;}if(saved.focus)stage.querySelector(`[data-field="${saved.focus}"]`)?.focus({preventScroll:true});updateRange();}
  function entry(d){
    const joining=location.hash.startsWith('#join/'),initial=joining?location.hash.split('/')[1]||'':'';
    const waiting=['connecting','reconnecting'].includes(d.status);
    return `<section class="game-page room-entry"><a class="back-link" href="#">← All games</a><div class="room-entry-heading"><span class="eyebrow">PULL UP A CHAIR</span><h1>A table for your people.</h1><p>Host on your computer. Friends join with a code. Let the good games begin.</p></div><div class="room-entry-grid"><form class="room-form" id="room-create"><span class="room-form-icon">✦</span><h2>Make a room</h2><p>You bring the code. They bring the competition.</p><label for="host-name">Your name</label><input id="host-name" name="name" autocomplete="nickname" maxlength="20" required placeholder="What should we call you?" value="${G.esc(name())}"><button class="button" ${waiting?'disabled':''}>${waiting&&d.isHost?'Opening your room…':'Create room'} <span aria-hidden="true">↗</span></button><span class="room-form-note">Free · Up to 8 friends · No account</span></form><form class="room-form" id="room-join"><span class="room-form-icon">↗</span><h2>Find your friends</h2><p>Got a room code? Your seat is waiting.</p><label for="guest-name">Your name</label><input id="guest-name" name="name" autocomplete="nickname" maxlength="20" required placeholder="Your player name" value="${G.esc(name())}"><label for="join-code">Room code</label><input id="join-code" name="code" class="room-code-input" maxlength="8" pattern="[A-Za-z2-9 -]{6,8}" autocapitalize="characters" autocomplete="off" spellcheck="false" required placeholder="ABC123" value="${G.esc(initial||d.code)}"><button class="button secondary" ${waiting?'disabled':''}>${waiting&&!d.isHost?'Finding your room…':'Join room'}</button></form></div>${d.error?`<div class="room-notice error" role="alert">${G.esc(d.error)}</div>`:''}${waiting?'<div class="room-progress" role="status"><span class="connection-spinner"></span> Connecting your table… <button class="text-button" data-room="cancel">Cancel</button></div>':''}<div class="room-entry-foot"><span>01 <strong>Create or join</strong></span><span>02 <strong>Pick a game together</strong></span><span>03 <strong>Everybody ready? Play.</strong></span></div><details class="connection-help"><summary>How online rooms work</summary><p>The host’s browser runs the room. Keep that tab open while you play. An internet connection is needed to create or join rooms; solo games work offline. On a network that blocks direct browser connections, try a different network.</p></details></section>`;
  }
  function people(d){const s=d.snapshot;return `<div class="room-sidebar"><h2>At the table <span>${s.players.length}/8</span></h2><div class="room-players">${s.players.map((p,i)=>`<div class="room-player ${p.id===s.me?'is-you':''}">${avatar(p,i)}<div><strong>${G.esc(p.name)} ${p.id===s.me?'<span class="you-label">you</span>':''}</strong><small>${p.host?'Host':!p.connected?'Reconnecting…':s.phase==='lobby'?(p.ready?'Ready to play':'Getting comfortable'):'At the table'}</small></div><span class="player-state ${p.connected&&(p.ready||s.phase==='playing')?'ready':''}">${!p.connected?'…':p.ready||s.phase==='playing'?'✓':'·'}</span></div>`).join('')}</div><div class="room-scoreboard"><span class="eyebrow">TONIGHT’S WINS</span>${s.players.map(p=>`<div><span>${G.esc(p.name)}</span><strong>${p.wins}</strong></div>`).join('')}</div><div class="room-reactions"><h3>Table talk</h3><div class="reaction-buttons">${['👏','😂','😮','🎉','🤔','💛'].map(e=>`<button data-room="reaction" data-emoji="${e}" aria-label="React ${e}">${e}</button>`).join('')}</div><div class="reaction-feed" aria-live="polite">${s.reactions.slice(-3).reverse().map(r=>`<div class="room-reaction"><span>${r.emoji}</span><small>${G.esc(r.name)}</small></div>`).join('')||'<small class="reaction-empty">A little friendly table talk.</small>'}</div></div></div>`;}
  function lobby(d){const s=d.snapshot,engine=RoomGames.games[s.gameId],me=s.players.find(p=>p.id===s.me);const count=s.players.filter(p=>p.connected).length;const canStart=count>=engine.min&&count<=engine.max&&s.players.every(p=>p.connected&&p.ready);
    return `<div class="room-lobby"><div class="room-lobby-intro"><span class="eyebrow">YOUR NEXT ROUND STARTS HERE</span><h2>${d.isHost?'Pick tonight’s first game.':'A good night is gathering.'}</h2><p>${d.isHost?'Share the code. Pick a game. Start when everyone is ready.':'Tell the host what you’re in the mood for, then press Ready.'}</p></div><div class="online-game-picker">${order.filter(id=>RoomGames.games[id]).map(id=>{const game=RoomGames.games[id],fits=count<=game.max;return `<button class="online-game-option ${s.gameId===id?'selected':''}" data-room="choose" data-game="${id}" aria-pressed="${s.gameId===id}" ${!d.isHost||!fits?'disabled':''}><span class="online-game-symbol">${icons[id]}</span><span><strong>${G.esc(game.title)}</strong><small>${game.min===game.max?game.min:game.min+'–'+game.max} players${!fits?' · Too many at the table':''}</small></span><span class="game-option-check">${s.gameId===id?'✓':''}</span></button>`;}).join('')}</div><div class="room-controls"><div><strong>${G.esc(engine.title)}</strong><p>${count<engine.min?'Invite '+(engine.min-count)+' more '+(engine.min-count===1?'friend':'friends')+' to play.':canStart?'Everybody is ready. Let’s play.':'Waiting for everyone to get ready.'}</p></div>${d.isHost?`<button class="button" data-room="start" ${canStart?'':'disabled'}>Start game →</button>`:`<button class="button ${me?.ready?'secondary':''}" data-room="ready">${me?.ready?'✓ Ready · click to undo':'I’m ready →'}</button>`}</div></div>`;
  }
  function playing(d){const s=d.snapshot,game=RoomGames.games[s.gameId];let body=game.render(s.game);const key=[s.gameId,s.epoch,s.game?.phase||'play',s.game?.round??'',s.game?.turn??''].join(':');
    return `<div class="room-match"><div class="room-match-heading"><div><span class="eyebrow">${s.done?'THAT’S A ROUND':'NOW AT YOUR TABLE'}</span><h2>${G.esc(game.title)}</h2></div>${d.isHost?'<button class="button secondary small" data-room="lobby">Back to lobby</button>':''}</div>${s.paused?'<div class="room-notice" role="status">A player disconnected. The game is paused while they rejoin. The host can return everyone to the lobby.</div>':''}<div class="game-surface room-stage ${s.paused?'room-paused':''}" data-key="${G.esc(key)}">${body}</div>${s.done?`<div class="room-controls room-result"><div><strong>Another round?</strong><p>Keep your room. Keep the good company.</p></div>${d.isHost?'<button class="button" data-room="rematch">Play again ↻</button><button class="button secondary" data-room="lobby">Pick another game</button>':'<span>Waiting for the host to pick the next round.</span>'}</div>`:''}<details class="online-rules"><summary>How to play ${G.esc(game.title)}</summary>${game.rules||G.games[s.gameId]?.rules||'<p>Follow the instructions at the table. Moves and scores are shared automatically.</p>'}<p>In a room, your friends take the other seats. The host chooses the next game.</p></details></div>`;
  }
  function render(){
    if(!root||!document.body.contains(root)||drawing)return;
    const saved=inputs(),d=R.data();
    if(!d.snapshot||['idle','ended'].includes(d.status)){root.innerHTML=entry(d);wireForms();return;}
    const s=d.snapshot;
    root.innerHTML=`<section class="game-page room-page"><div class="room-topbar"><a class="back-link" href="#">← Game library</a><span class="room-pill"><span class="connection-dot ${d.status==='connected'?'':'connecting'}"></span>${d.status==='connected'?'Live room':d.status==='reconnecting'?'Reconnecting':'Connection interrupted'}</span><button class="text-button" data-room="leave">${d.isHost?'Close room':'Leave room'}</button></div><div class="room-heading"><div><span class="eyebrow">${d.isHost?'YOU’RE HOSTING':'YOU’RE INVITED'}</span><h1>${s.phase==='lobby'?'The gang’s all here.':'Let’s play.'}</h1><p>${d.isHost?'Keep this tab open — your computer hosts the room.':'Your friends, one shared table. Make yourself at home.'}</p></div><div class="room-code-card"><span>INVITE YOUR FRIENDS</span><button class="room-code" data-room="copy" aria-label="Copy room code ${G.esc(d.code)}">${G.esc(d.code)} <small>⧉</small></button><small>They open VectorSpace and enter this code.</small></div></div>${d.error?`<div class="room-notice error" role="alert">${G.esc(d.error)} ${d.status==='error'?'<button class="text-button" data-room="retry">Retry connection</button>':''}</div>`:''}${notice?`<div class="room-notice" role="status">${G.esc(notice)}</div>`:''}<div class="room-layout"><div>${s.phase==='lobby'?lobby(d):playing(d)}</div>${people(d)}</div></section>`;
    if(s.paused||d.status!=='connected')root.querySelectorAll('[data-move]').forEach(b=>b.disabled=true);
    restore(saved);updateRange();setupDrawing();
  }
  function wireForms(){
    root.querySelector('#room-create')?.addEventListener('submit',e=>{e.preventDefault();const name=root.querySelector('#host-name').value.trim();if(!name)return;saveName(name);R.create(name,preferred);});
    root.querySelector('#room-join')?.addEventListener('submit',e=>{e.preventDefault();const name=root.querySelector('#guest-name').value.trim(),code=root.querySelector('#join-code').value;if(!name)return;saveName(name);R.join(name,code);});
  }
  function updateRange(){root?.querySelectorAll('input[type="range"][data-field]').forEach(input=>{const output=root.querySelector(`[data-value-for="${input.dataset.field}"],[data-range-output="${input.dataset.field}"]`);if(output)output.textContent=input.value;const marker=root.querySelector('[data-guess-marker],.guess-marker');if(marker)marker.style.left=input.value+'%';});}
  function setupDrawing(){
    const canvas=root?.querySelector('[data-drawing-canvas]');if(!canvas)return;
    const v=R.data().snapshot?.game;if(!v)return;
    const context=canvas.getContext('2d');context.fillStyle=v.background||'#ffffff';context.fillRect(0,0,canvas.width,canvas.height);
    const paint=stroke=>{const points=stroke.points;if(!points?.length)return;context.strokeStyle=stroke.color;context.fillStyle=stroke.color;context.lineWidth=stroke.width;context.lineCap='round';context.lineJoin='round';if(points.length===1){context.beginPath();context.arc(points[0][0]*canvas.width,points[0][1]*canvas.height,stroke.width/2,0,Math.PI*2);context.fill();return;}context.beginPath();context.moveTo(points[0][0]*canvas.width,points[0][1]*canvas.height);points.slice(1).forEach(p=>context.lineTo(p[0]*canvas.width,p[1]*canvas.height));context.stroke();};
    (v.strokes||[]).forEach(paint);
    const color=root.querySelector('[data-draw-color]'),width=root.querySelector('[data-draw-width]');
    if(color){if([...color.options].some(o=>o.value===brushColor))color.value=brushColor;else brushColor=color.value;color.onchange=()=>brushColor=color.value;}
    if(width){width.value=brushWidth;width.oninput=()=>{brushWidth=width.value;const out=root.querySelector('[data-brush-size]');if(out)out.textContent=width.value;};}
    if(!v.canDraw||R.data().snapshot.paused)return;
    const point=e=>{const bounds=canvas.getBoundingClientRect();return [Math.max(0,Math.min(1,(e.clientX-bounds.left)/bounds.width)),Math.max(0,Math.min(1,(e.clientY-bounds.top)/bounds.height))].map(x=>Math.round(x*10000)/10000);};
    const flush=()=>{if(!drawing||!drawing.points.length)return;const points=drawing.points.map(p=>[...p]);R.move({type:'stroke',round:v.round,points,color:drawing.color,width:drawing.width});drawing.points=[points.at(-1)];drawing.lastSend=Date.now();};
    canvas.onpointerdown=e=>{if(e.button!==0&&e.pointerType==='mouse')return;e.preventDefault();canvas.setPointerCapture(e.pointerId);drawing={pointer:e.pointerId,points:[point(e)],color:color?.value||brushColor,width:Number(width?.value||brushWidth),lastSend:Date.now()};paint({points:drawing.points,color:drawing.color,width:drawing.width});};
    canvas.onpointermove=e=>{if(!drawing||drawing.pointer!==e.pointerId)return;e.preventDefault();const next=point(e),last=drawing.points.at(-1);drawing.points.push(next);paint({points:[last,next],color:drawing.color,width:drawing.width});if(drawing.points.length>=48||Date.now()-drawing.lastSend>=180)flush();};
    const finish=e=>{if(!drawing||drawing.pointer!==e.pointerId)return;flush();drawing=null;try{canvas.releasePointerCapture(e.pointerId);}catch{}render();};
    canvas.onpointerup=finish;canvas.onpointercancel=finish;canvas.onlostpointercapture=finish;
  }
  function mount(element,game){root=element;preferred=RoomGames.games[game]?game:'color-clash';
    root.onclick=e=>{const move=e.target.closest('[data-move]');if(move&&!move.disabled){const action={...move.dataset,type:move.dataset.move};delete action.move;root.querySelectorAll('[data-field]').forEach(field=>{if(field.type!=='checkbox'||field.checked)action[field.dataset.field]=field.value;});R.move(action);return;}const b=e.target.closest('[data-room]');if(!b||b.disabled)return;const d=R.data();switch(b.dataset.room){case'choose':R.choose(b.dataset.game);break;case'start':case'rematch':R.start();break;case'lobby':R.backToLobby();break;case'ready':R.ready(!d.snapshot.players.find(p=>p.id===d.myId)?.ready);break;case'reaction':R.react(b.dataset.emoji);break;case'copy':copy(d.code);break;case'leave':R.leave();location.hash='online';break;case'cancel':R.leave();break;case'retry':R.retry();break;}};
    root.oninput=updateRange;root.onkeydown=e=>{if(e.key==='Enter'&&e.target.matches('input[data-field]:not([type="range"])')){const field=e.target.dataset.field,type=e.target.dataset.submit||({message:'message',clue:'clue',guess:'guess',hint:'hint'}[field]);if(type){const target=root.querySelector(`[data-move="${type}"]:not(:disabled)`);if(target){e.preventDefault();target.click();}}}};unsubscribe=R.subscribe(render);render();
    return ()=>{unsubscribe?.();unsubscribe=null;drawing=null;if(root===element){root.onclick=null;root.oninput=null;root.onkeydown=null;root=null;}};
  }
  return {mount,render};
})();
